sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[文档](/wiki/)'
    notes: '[便笺](/notes/)'
    more: '[更多](/about/)'

article:
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
    '设计开发': '#03a9f4'
    # '奇思妙想': '#009688'
    '解决方案': '#ff9800'
    '技术加油站': '#4caf50'
    '开源库': '#4caf50'
    '博客主题': '#ffa000'
    # '应用程序': '#e91e63'
    # '实用脚本': '#009688'
  share: [wechat, weibo, email, link]
  related_posts:
    enable: true

comments:
  service: utterances
  utterances:
    repo: xaoxuu/blog-comments

footer:
  social:
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/xaoxuu
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
      url: https://open.spotify.com/user/xaoxuu
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3616429.svg"/>'
      url: https://unsplash.com/@xaoxuu
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
      url: /about/#comments

  source: '[GitHub](https://github.com/xaoxuu/xaoxuu.github.io/)'
